# Generated by Django 5.2.17 on 2026-09-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_published_on_post_published_on_idx'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE core_post SET published_on = created_at::date, "
            "published_on_idx = created_at::date",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
