# Generated by Django 5.2.17 on 2026-09-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_pulished_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_on_idx',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
