# Generated by Django 5.2.17 on 2026-09-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_comment_count'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE core_post p SET comment_count="
            " (SELECT count(*) FROM core_comment c WHERE c.post_id = p.id)",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
