# Generated by Django 5.2.17 on 2026-09-12 08:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('title', 'body', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_post_search__69a8d4_gin'),
        ),
    ]
