from django.urls import path

from . import lab01, lab02, lab03, lab04, lab05, lab06, lab07, lab08, lab09, views

urlpatterns = [
    path("health/", views.Health.as_view()),
    path("01/bad/", lab01.PostListBad.as_view()),
    path("01/good/", lab01.PostListGood.as_view()),
    path("01/trap/", lab01.PostListTrap.as_view()),
    path("01/trap-fixed/", lab01.PostListTrapFixed.as_view()),
    path("02/bad/", lab02.PostByDateBad.as_view()),
    path("02/good/", lab02.PostByDateGood.as_view()),
    path("03/bad/", lab03.HasCommentsBad.as_view()),
    path("03/good/", lab03.HasCommentsGood.as_view()),
    path("03/page-counted/", lab03.PostsPageCounted.as_view()),
    path("03/page-nocount/", lab03.PostsPageNoCount.as_view()),
    path("03/count-exact/", lab03.PostCountExact.as_view()),
    path("03/count-approx/", lab03.PostCountApprox.as_view()),
    path("04/full/", lab04.TitlesFull.as_view()),
    path("04/only/", lab04.TitlesOnly.as_view()),
    path("04/values/", lab04.TitlesValues.as_view()),
    path("04/defer-trap/", lab04.DeferTrap.as_view()),
    path("05/bad/", lab05.AllPosts.as_view()),
    path("05/good/", lab05.PagedPosts.as_view()),
    path("06/bad/<int:pk>/", lab06.PostDetailBad.as_view()),
    path("06/good/<int:pk>/", lab06.PostDetailGood.as_view()),
    path("07/bad/", lab07.PostsGenericLikes.as_view()),
    path("07/good/", lab07.PostsConcreteLikes.as_view()),
    path("07/feed/", lab07.LikesFeed.as_view()),
    path("07/feed-fixed/", lab07.LikesFeedFixed.as_view()),
     path("08/bad/", lab08.LikeCountsUncached.as_view()),
    path("08/good/", lab08.LikeCountsCached.as_view()),
    path("08/orm-write/", lab08.OrmWrite.as_view()),
    path("08/raw-write/", lab08.RawWrite.as_view()),
    path("09/wrong/", lab09.PostStatsWrong.as_view()),
    path("09/bad/", lab09.PostStatsBad.as_view()),
    path("09/good/", lab09.PostStatsGood.as_view()),
]